// File generated by flutterfire configure
// This is a placeholder - run `flutterfire configure` to generate the real file
// For testing purposes, this minimal version allows the app to start

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACnYX8HE79nXBP2MGTxcS0571tG5FRPiQ',
    appId: '1:278844489900:web:c03f690c64fe73dc295f09',
    messagingSenderId: '278844489900',
    projectId: 'flutter-72c45',
    authDomain: 'flutter-72c45.firebaseapp.com',
    storageBucket: 'flutter-72c45.firebasestorage.app',
    measurementId: 'G-P5HJSR848G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV45kIlbbDQP_bNwhAF_LqROiR5Eaa7hg',
    appId: '1:278844489900:android:348779b4f63ef20d295f09',
    messagingSenderId: '278844489900',
    projectId: 'flutter-72c45',
    storageBucket: 'flutter-72c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_x9rfwaSuVt3BvUsd6mSW6rfkJHevIks',
    appId: '1:278844489900:ios:27ebca117404c488295f09',
    messagingSenderId: '278844489900',
    projectId: 'flutter-72c45',
    storageBucket: 'flutter-72c45.firebasestorage.app',
    iosBundleId: 'com.example.shopFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo:macos:demo',
    messagingSenderId: 'demo',
    projectId: 'shop-flutter-demo',
    iosBundleId: 'com.example.shopFlutter',
  );
}
