// File generated by flutterfire configure
// This is a placeholder - run `flutterfire configure` to generate the real file
// For testing purposes, this minimal version allows the app to start

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo:web:demo',
    messagingSenderId: 'demo',
    projectId: 'shop-flutter-demo',
    authDomain: 'shop-flutter-demo.firebaseapp.com',
    storageBucket: 'shop-flutter-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo:android:demo',
    messagingSenderId: 'demo',
    projectId: 'shop-flutter-demo',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo:ios:demo',
    messagingSenderId: 'demo',
    projectId: 'shop-flutter-demo',
    iosBundleId: 'com.example.shopFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:demo:macos:demo',
    messagingSenderId: 'demo',
    projectId: 'shop-flutter-demo',
    iosBundleId: 'com.example.shopFlutter',
  );
}

